// src/components/features/gto/gto.data.ts
// 프론트 즉시 렌더링용 더미 GTO 데이터 (BTN RFI / BTN vs UTG / BB vs BTN)
import type { GtoScenario } from './gto.types';

export const GTO_SCENARIOS: readonly GtoScenario[] = [
  {
    id: 'btn-rfi-100',
    label: 'BTN 오픈 (RFI)',
    description: '버튼에서 첫 오픈 레이즈. 100bb 캐시.',
    street: 'preflop',
    heroPosition: 'BTN',
    villain: null,
    stackDepthBb: 100,
    gameType: 'cash',
    source: 'dummy',
    strategy: {
      'AA': { raise: 1, call: 0, fold: 0 }, 'KK': { raise: 1, call: 0, fold: 0 },
      'QQ': { raise: 1, call: 0, fold: 0 }, 'JJ': { raise: 1, call: 0, fold: 0 },
      'TT': { raise: 1, call: 0, fold: 0 }, '99': { raise: 1, call: 0, fold: 0 },
      '88': { raise: 1, call: 0, fold: 0 }, '77': { raise: 1, call: 0, fold: 0 },
      '66': { raise: 1, call: 0, fold: 0 }, '55': { raise: 1, call: 0, fold: 0 },
      '44': { raise: 1, call: 0, fold: 0 }, '33': { raise: 1, call: 0, fold: 0 },
      '22': { raise: 0.9, call: 0, fold: 0.1 },
      'AKs': { raise: 1, call: 0, fold: 0 }, 'AQs': { raise: 1, call: 0, fold: 0 },
      'AJs': { raise: 1, call: 0, fold: 0 }, 'ATs': { raise: 1, call: 0, fold: 0 },
      'A5s': { raise: 1, call: 0, fold: 0 }, 'A2s': { raise: 1, call: 0, fold: 0 },
      'AKo': { raise: 1, call: 0, fold: 0 }, 'AQo': { raise: 1, call: 0, fold: 0 },
      'AJo': { raise: 1, call: 0, fold: 0 }, 'ATo': { raise: 1, call: 0, fold: 0 },
      'A9o': { raise: 0.6, call: 0, fold: 0.4 },
      'KQs': { raise: 1, call: 0, fold: 0 }, 'KJs': { raise: 1, call: 0, fold: 0 },
      'KTs': { raise: 1, call: 0, fold: 0 }, 'K9s': { raise: 1, call: 0, fold: 0 },
      'KQo': { raise: 1, call: 0, fold: 0 }, 'KJo': { raise: 1, call: 0, fold: 0 },
      'KTo': { raise: 0.8, call: 0, fold: 0.2 }, 'K9o': { raise: 0.45, call: 0, fold: 0.55 },
      'QJs': { raise: 1, call: 0, fold: 0 }, 'QTs': { raise: 1, call: 0, fold: 0 },
      'QJo': { raise: 1, call: 0, fold: 0 }, 'QTo': { raise: 0.7, call: 0, fold: 0.3 },
      'JTs': { raise: 1, call: 0, fold: 0 }, 'JTo': { raise: 0.6, call: 0, fold: 0.4 },
      'T9s': { raise: 1, call: 0, fold: 0 }, '98s': { raise: 1, call: 0, fold: 0 },
      '87s': { raise: 1, call: 0, fold: 0 }, '76s': { raise: 1, call: 0, fold: 0 },
      '65s': { raise: 1, call: 0, fold: 0 }, '54s': { raise: 1, call: 0, fold: 0 },
      '72o': { raise: 0, call: 0, fold: 1 },
    },
  },
  {
    id: 'btn-vs-utg-raise-100',
    label: 'BTN vs UTG 레이즈',
    description: 'UTG 2.5bb 오픈에 대한 버튼의 3벳/콜/폴드. 100bb.',
    street: 'preflop',
    heroPosition: 'BTN',
    villain: { position: 'UTG', action: 'raise', sizingBb: 2.5 },
    stackDepthBb: 100,
    gameType: 'cash',
    source: 'dummy',
    strategy: {
      'AA': { raise: 1, call: 0, fold: 0 }, 'KK': { raise: 1, call: 0, fold: 0 },
      'QQ': { raise: 0.85, call: 0.15, fold: 0 }, 'JJ': { raise: 0.4, call: 0.6, fold: 0 },
      'TT': { raise: 0.1, call: 0.9, fold: 0 }, '99': { raise: 0, call: 1, fold: 0 },
      '88': { raise: 0, call: 0.8, fold: 0.2 }, '77': { raise: 0, call: 0.6, fold: 0.4 },
      'AKs': { raise: 1, call: 0, fold: 0 }, 'AKo': { raise: 0.9, call: 0.1, fold: 0 },
      'AQs': { raise: 0.4, call: 0.6, fold: 0 }, 'AQo': { raise: 0.25, call: 0.15, fold: 0.6 },
      'AJs': { raise: 0.1, call: 0.9, fold: 0 }, 'ATs': { raise: 0, call: 1, fold: 0 },
      'A5s': { raise: 0.5, call: 0.1, fold: 0.4 }, 'A4s': { raise: 0.35, call: 0, fold: 0.65 },
      'KQs': { raise: 0.2, call: 0.8, fold: 0 }, 'KJs': { raise: 0, call: 0.7, fold: 0.3 },
      'KTs': { raise: 0, call: 0.5, fold: 0.5 }, 'QJs': { raise: 0, call: 0.5, fold: 0.5 },
      'JTs': { raise: 0, call: 0.6, fold: 0.4 }, 'T9s': { raise: 0, call: 0.3, fold: 0.7 },
      '98s': { raise: 0, call: 0.2, fold: 0.8 }, 'AJo': { raise: 0, call: 0, fold: 1 },
      '72o': { raise: 0, call: 0, fold: 1 },
    },
  },
  {
    id: 'bb-vs-btn-raise-100',
    label: 'BB vs BTN 레이즈',
    description: 'BTN 2.5bb 오픈에 대한 빅블라인드 디펜스(콜 와이드 + 일부 3벳). 100bb.',
    street: 'preflop',
    heroPosition: 'BB',
    villain: { position: 'BTN', action: 'raise', sizingBb: 2.5 },
    stackDepthBb: 100,
    gameType: 'cash',
    source: 'dummy',
    strategy: {
      'AA': { raise: 1, call: 0, fold: 0 }, 'KK': { raise: 1, call: 0, fold: 0 },
      'QQ': { raise: 0.8, call: 0.2, fold: 0 }, 'JJ': { raise: 0.5, call: 0.5, fold: 0 },
      'TT': { raise: 0.2, call: 0.8, fold: 0 }, '99': { raise: 0.1, call: 0.9, fold: 0 },
      '88': { raise: 0, call: 1, fold: 0 }, '55': { raise: 0, call: 1, fold: 0 },
      '22': { raise: 0, call: 1, fold: 0 },
      'AKs': { raise: 1, call: 0, fold: 0 }, 'AKo': { raise: 0.7, call: 0.3, fold: 0 },
      'AQs': { raise: 0.5, call: 0.5, fold: 0 }, 'AQo': { raise: 0.2, call: 0.8, fold: 0 },
      'AJo': { raise: 0, call: 1, fold: 0 }, 'A5s': { raise: 0.6, call: 0.4, fold: 0 },
      'A2s': { raise: 0, call: 1, fold: 0 }, 'KQs': { raise: 0.3, call: 0.7, fold: 0 },
      'KTo': { raise: 0, call: 1, fold: 0 }, 'QJo': { raise: 0, call: 1, fold: 0 },
      'JTs': { raise: 0, call: 1, fold: 0 }, 'T9s': { raise: 0, call: 1, fold: 0 },
      '76s': { raise: 0, call: 1, fold: 0 }, '54s': { raise: 0, call: 0.9, fold: 0.1 },
      'J5o': { raise: 0, call: 0.4, fold: 0.6 }, '93o': { raise: 0, call: 0.2, fold: 0.8 },
      '72o': { raise: 0, call: 0, fold: 1 },
    },
  },
] as const;

export const DEFAULT_SCENARIO_ID = GTO_SCENARIOS[0].id;
